[package]
name = "dynahist_rust"
version = "0.1.0"
edition = "2018"
resolver = "2"

[lib]
name = "dynahist"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
utilities = { path = "utilities" }

[features]
test-traits = []
